[env:esp32s3_n16r8]
platform = espressif32
board = esp32s3box
framework = arduino
monitor_speed = 115200

; Config for ESP32-S3 N16R8 (16MB Flash, 8MB PSRAM)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.prsam_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

; Partition table (large app, SPIFFS)
board_build.partitions = default_16MB.csv

; Build flags for PSRAM and C++17
build_flags =
    -DBOARD_HAS_PSRAM
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=0
build_unflags =
    -std=gnu++11

lib_deps =
    sensirion/Sensirion I2C SCD4x @ ^1.0.4
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.14
