[env:esp32s3_n16r8]
platform = espressif32 @ 6.6.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Config for ESP32-S3 N16R8 (16MB Flash, 8MB PSRAM)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.prsam_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

; Partition table (large app, SPIFFS)
board_build.partitions = default_16MB.csv

; Build flags for PSRAM and C++17
build_flags =
    -DBOARD_HAS_PSRAM
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=0
    ; TFT_eSPI Settings
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_CS=10
    -DTFT_DC=13
    -DTFT_RST=14
    -DTFT_BL=15
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_FONT8=1
    -DSPI_FREQUENCY=40000000
build_unflags =
    -std=gnu++11

lib_deps =
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.14
    tanakamasayuki/TensorFlowLite_ESP32 @ ^1.0.0
    bodmer/TFT_eSPI @ ^2.5.43
    https://github.com/tzapu/WiFiManager.git
